### PR TITLE
Added chimeric and unique modes from Perl version

### PR DESCRIPTION
**Pull request by PolinaBevad**
### Description
There are changes in Perl version from commit https://github.com/AstraZeneca-NGS/VarDict/commit/97e41ebd05cf5469c9d74d2f509024197f598d04, that must be implemented in Java in the first place: 
`-u` (option to process overlapped portion of mate pairs only once) 
`--chimeric` (chimeric artifacts from library constructions, default run). 

### Implementation

- Added options `-u` and `--chimeric` and implemented logic for them. Old logic of overlapping reads was changed in the same way as it was implemented by Zhongwu Lai in commit above.
- Changed method `isGoodVar()` for detection of good variations (also from Zhongwu Lai commit).
- The `goodq` is now the floating-point number (`-q` option, default `22.5`).
- Added new integrations tests for this cases and fixed old tests, now the results are closer to Perl version, but there are still many differences between Perl and Java versions, that need to be implemented later.

### Performance measurements 
All Java measurements are made with -th 8 option. 

File | Master Java before changes | New Java without options | New Java with -u | New Java with --chimeric | New Java with -u and --chimeric | Perl without options
-- | -- | -- | -- | -- | -- | --
AURA_26-ready.bam1,5 Gb |  5 min 10.31 sec | 6 min 34.64 sec | 5 min 6.39 sec | 6 min 33.07 sec | 4 min 55.72 sec | 11 hours 25 minutes

The performance for -u mode is now the same as was before (when this mode was by default).

### CODE REVIEW

**Comment by mjafin** [comment]
Just to understand this correctly, with `-u` only one read will be processed from an overlapping pair (as here https://github.com/AstraZeneca-NGS/VarDictJava/issues/60) and without `-u` we revert to old way of ignoring the fact that the reads are overlapping (and therefore count twice)?

**Comment by PolinaBevad** [comment]
@mjafin , Exactly! And also the overlap detection algorithm is now identical to perl detection.

**Comment by mjafin** [comment]
Could you summarise how the logic is different to the previous implementation please?

**Comment by PolinaBevad** [comment]
@mjafin , in the previous implementation read was skipped if it was in forward direction, the mate of read was in reverse direction, start of mate was less than or equal to read end and the start of read was more than or equal to the start of mate. Also chromosomes of mate and read must be the same. 

Now read is skipped only if unique mode enabled and read is in forward direction with start of read more than or equal to the start of mate. Also it is skipped now at the very beginning of the processing Cigar.

Perhaps there is a question about the same chromosomes, but it is not checked in perl now. Do you think we must leave this check?

**Comment by mjafin** [comment]
I'm struggling to understand how the changes affect the logic. Maybe Zhongwu @zhongwulai could comment on why the Perl fix was different from Java fix?

Further, does it address the strand bias issue discussed here (I suspect not): https://github.com/AstraZeneca-NGS/VarDictJava/issues/102

**Comment by PolinaBevad** [comment]
@mjafin , of course, let's wait for the answer of Zhongwu.  
The strand bias issue for variation in the https://github.com/AstraZeneca-NGS/VarDictJava/issues/102 is fixed for this concrete variation (T->A), but because of another changes in perl version: now frequency with bias (2;1) must be more than 20 (was 25) to detect it as good var.

**Comment by zhongwulai** [comment]
@PolinaBevad You're right, the chromosome check should be added ($a[6] eq "=").   So please go ahead and add the check.  When -u option is enabled, it doesn't skip the read completely, it only skips the overlapping portion in the first read.  The part I don't understand is why the performance decreases significantly.

**Comment by PolinaBevad** [comment]
@zhongwulai , thanks! I added this check.
We also found that there are some problems with java optimizations on large methods (in this case method `parseSam()`), so some refactoring was done to avoid this and now the performance is almost the same as before. The new measurements are given in the table.

**Comment by PolinaBevad** [comment]
@mjafin, can we merge this PR or do you have any other comments?

**Comment by zhongwulai** [comment]
I'm OK with current implementation.  Many thanks!

**Comment by mjafin** [comment]
@nh13 ?

**Comment by nh13** [comment]
On vacation for two weeks. I can respond then if you still need my input.

**Pull request merged**
