### PR TITLE
Add an option to include Ns in the total depth

### PR DESCRIPTION
**Pull request by nh13**
In sequencing assays that generate consensus calls from reads observing the same source molecule (ex. reads with UMIs), sometimes consensus calls are made with Ns.  While the exact base cannot be determined for the molecule, it is useful to have the Ns contribute to the total coverage for more accurate allele frequency estimation.  This change will effect the final value put in the `DP` format field when the `-j` option is used.  When in use, the total depth without Ns can still be obtained using the sum of the values in the `VD` format field.  If this change is not acceptable, I would welcome guidance on how to add an additional FORMAT field to track the # of Ns at any site.

### CODE REVIEW

**Comment by mjafin** [comment]
Hi Nils,
I have to leave this for @zhongwulai to comment on and approve or disagree

**Comment by clintval** [comment]
I also work with consensus sequencing and would benefit from having the option to obtain Ns *per* call. +1 for me. Thanks for the review!

**Comment by nh13** [comment]
@zhongwulai I wanted to see if you had a chance to look?

**Comment by zhongwulai** [comment]
I'm wondering, from your experience, how often do you see number of Ns counts exceeds the mutant allele?  The simplest update would be to treat N as an allele, but would require further modifications in VCF conversion if N exceeds mutant allele.  Or you just want to add Ns to the DP but also track # of Ns for all variant called, e.g. a property in FORMAT field in VCF?  Also, how often do you see consecutive Ns in a consensus read?

**Comment by nh13** [comment]
@zhongwulai we often see one or more Ns in a single read, and even runs of Ns are not uncommon, depending on how we filter and mask the reads (mask means we set the base to N).  In many cases, the # of Ns exceeds the # of observations of the mutant allele, as we are looking at extremely low frequency variants (say 1 in 10K, to 1 in 1M).  We want to treat the Ns as adding to the total depth (how many reads covered this position), but not to the depth of the variant alleles, so having the `DP` in the `FORMAT` field include the count of Ns.  It is fine to have `N` not be its own allele and not counted in the `VD` (variant depth) in the `FORMAT` field for that sample.  This was the intention of my PR.  Thanks for responding!

**Comment by zhongwulai** [comment]
@nh13 I think I have a working version, which will take an option "-K" and count Ns toward's total DP, but won't output N as an allele.  I also make processing overlapping mate as an option, not default, as we have observed that it can lose some sensitivity for non-UMI sequencing.  Can I send the source code to you (three .java files modified) to test before I commit to Github?

**Comment by nh13** [comment]
@zhongwulai please do. Let me know if you don’t have my email already.

**Comment by zhongwulai** [comment]
@nh13 looks good to me.  Can you change the option from -j to -K (capital)?  I have -j and -J reserved for CRISPR variant calling.  After that I can merge the pull.  Thanks!

**Comment by nh13** [comment]
@zhongwulai I updated the commit to change `-j` to `-K` as suggested.  Nonetheless, I am a bit confused by your last two comments, since you suggested you have some code (three java files) for testing.  Would you like me to test those, or is this PR sufficient?

**Comment by nh13** [comment]
@zhongwulai just checking in to see what you think!

**Comment by nh13** [comment]
@zhongwulai what's left for us to get this in? I'd like to start using it in our production pipelines.

**Comment by nh13** [comment]
@zhongwulai @mjafin can you merge this?

**Comment by mjafin** [comment]
I have asked our collaborators to look at testing and merging this one, sorry about the delays.

**Comment by nkarulin** [comment]
@nh13, thank you for the contribution! 
Could you please provide corresponding auto tests extension, which will cover new functionality? There are data driven integration tests now in VarDict (https://github.com/AstraZeneca-NGS/VarDictJava/pull/78/), you could find instruction how to easily extend them in README: https://github.com/AstraZeneca-NGS/VarDictJava#user-extension-of-testcases.
If you have any questions, please feel free to ask.

**Comment by nh13** [comment]
@nkarulin I added my own, which I tried to make purposely fail, and it doesn't look like the tests ran.  Any help would be appreciated:
```
Nils:VarDictJava nhomer$ ./gradlew test --tests com.astrazeneca.vardict.integrationtests.IntegrationTest
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2.252 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html
```

**Comment by nh13** [comment]
Answering my own question, apparently I need to run `cleanTest` before each execution, or add it to the build file.

**Comment by nh13** [comment]
@nkarulin I tried deleting a few lines from the `Amplicon;hg19.fa;Colo829-18_S3-sort.bam;chr1;933866-934466;933866-934466;-a 100.95 -D;.txt` file, which _I think_ should have made the tests fail, but there was no failure.  I am very unfamiliar with gradle, what am I missing?

**Comment by nh13** [comment]
@nkarulin ok I found the output and made a commit to the Readme to make it clearer where to find it (it wasn't clear to me).

**Comment by nh13** [comment]
@nkarulin tests added (and copied the relevant lines):

(1) a test to show that _without_ the `-K` option, the N in the read _is not_ counted

```
Count-Depth-With-Ns testbed chr1    391321  391321  G   C   3   1   0   1   0   1   G/C 0.3333  0;0 1.0 0   27.0    0   0.0 2.000   0.5000  0   0   1.000   1   0.0 1   2   GGTAGACTGTGTTTAGGTGG    CATGGTGGTGCATACCTGTG    chr1:391311-391333  SNV
```

(2) a test to show that _with_ the `-K` option, the N in the read _is_ counted

```
Count-Depth-With-Ns testbed chr1    391321  391321  G   C   2   1   0   1   0   1   G/C 0.5000  0;0 1.0 0   27.0    0   0.0 2.000   0.5000  0   0   1.000   1   0.0 1   2   GGTAGACTGTGTTTAGGTGG    CATGGTGGTGCATACCTGTG    chr1:391311-391333  SNV
```

See column 8

**Comment by nkarulin** [comment]
Hello, @nh13! Thank you very much for the tests extension. New tests work like a charm.
Sorry for not answering operatively, we have had night here. But I'am glad you could puzzle out our small integration testing system.
For me now we could merge changes.

**Comment by mjafin** [comment]
Thanks all for fixing the issue and the effort, much appreciated.

**Pull request merged**
